export const uiAssets = {
  panelMenu: '/assets/png/default/ui/menu/panel_menu.png',
  titlePirateBattle: '/assets/png/default/ui/menu/title_pirate_battle.png',
  buttonPrimaryNormal: '/assets/png/default/ui/menu/button_primary_normal.png',
  buttonPrimaryHover: '/assets/png/default/ui/menu/button_primary_hover.png',
  buttonPrimaryPressed: '/assets/png/default/ui/menu/button_primary_pressed.png',
  buttonPrimaryDisabled: '/assets/png/default/ui/menu/button_primary_disabled.png',
  buttonSecondaryNormal: '/assets/png/default/ui/menu/button_secondary_normal.png',
  buttonSecondaryPressed: '/assets/png/default/ui/menu/button_secondary_pressed.png',
  buttonRoundNormal: '/assets/png/default/ui/controls/button_round_normal.png',
  buttonRoundHover: '/assets/png/default/ui/controls/button_round_hover.png',
  buttonRoundPressed: '/assets/png/default/ui/controls/button_round_pressed.png',
  counterPanel: '/assets/png/default/ui/hud/counter_panel.png',
  healthFrame: '/assets/png/default/ui/hud/health_frame.png',
  healthFillGreen: '/assets/png/default/ui/hud/health_fill_green.png',
  healthFillAmber: '/assets/png/default/ui/hud/health_fill_amber.png',
  healthFillRed: '/assets/png/default/ui/hud/health_fill_red.png',
  iconClose: '/assets/png/default/ui/controls/icon_close.png',
  iconHome: '/assets/png/default/ui/controls/icon_home.png',
  iconMinus: '/assets/png/default/ui/controls/icon_minus.png',
  iconPause: '/assets/png/default/ui/controls/icon_pause.png',
  iconPlay: '/assets/png/default/ui/controls/icon_play.png',
  iconPlus: '/assets/png/default/ui/controls/icon_plus.png',
  iconRestart: '/assets/png/default/ui/controls/icon_restart.png',
  iconScore: '/assets/png/default/ui/hud/icon_score.png',
  iconSettings: '/assets/png/default/ui/controls/icon_settings.png',
  iconTime: '/assets/png/default/ui/hud/icon_time.png',
  iconHeart: '/assets/png/default/ui/hud/icon_heart.png',
  iconFireFront: '/assets/png/default/ui/controls/icon_fire_front.png',
  iconFireLeft: '/assets/png/default/ui/controls/icon_fire_left.png',
  iconFireRight: '/assets/png/default/ui/controls/icon_fire_right.png',
  iconForward: '/assets/png/default/ui/controls/icon_forward.png',
} as const;

export type UiAssetName = keyof typeof uiAssets;
